version: '3'
services:
  php:
    build: "./docker/php"
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravelapp
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
       - redis-data:/data
  horizon:
    build: "./docker/horizon"
    volumes:
      - ./:/var/www/html
volumes:
  data-volume:
  redis-data:
